defmodule HgsBrain.ArcanaClient do
  @moduledoc """
  Behaviour defining the subset of the Arcana API used by this application.

  The default implementation delegates to the `Arcana` module. In tests,
  `HgsBrain.MockArcanaClient` (generated by Mox) is substituted via
  application config.
  """

  @callback ingest_file(Path.t(), keyword()) :: {:ok, map()} | {:error, term()}
  @callback ask(String.t(), keyword()) :: {:ok, String.t(), list()} | {:error, term()}
  @callback search(String.t(), keyword()) :: list()
  @callback delete(binary(), keyword()) :: :ok | {:error, :not_found}
end
